### ISSUE TITLE
panic on database shutdown

### ISSUE THREAD

**Issue by dimalinux** [AthanorLabs/atomic-swap#208]
By accident I typed `swapd` instead of `swapcli` and discovered this panic. It's unrelated to what I'm working on now, so just ticketing it. Based on the output, it looks related to the database close.
```
$ ./swapd balance --swapd-port 5001
2022-10-22T17:17:55.443-0500	ERROR	cmd	swapd/main.go:270	failed to make daemon: dial tcp 127.0.0.1:8545: connect: connection refused
protocol complete, shutting down...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfa6081]

goroutine 1 [running]:
github.com/athanorlabs/atomic-swap/db.(*Database).Close(...)
	/home/dima/dev/atomic-swap/db/database.go:36
main.(*daemon).stop(0xc000a27e80)
	/home/dima/dev/atomic-swap/cmd/swapd/main.go:286 +0x21
main.runDaemon(0xc000a27e00)
	/home/dima/dev/atomic-swap/cmd/swapd/main.go:277 +0x15e
github.com/urfave/cli/v2.(*App).RunContext(0x1f29d00, {0x1733c80?, 0xc0000400d0}, {0xc00003c080, 0x4, 0x4})
	/home/dima/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/app.go:350 +0x9d3
github.com/urfave/cli/v2.(*App).Run(...)
	/home/dima/go/pkg/mod/github.com/urfave/cli/v2@v2.10.2/app.go:247
main.main()
	/home/dima/dev/atomic-swap/cmd/swapd/main.go:201 +0x47
```

**Comment by noot** [comment]
@dimalinux just needs a nil check before closing, let me know if you've fixed this or I can do it

**Comment by dimalinux** [comment]
I didn't have time to look into it. Go ahead and fix it, especially since you know the fix!
